SC_uint(_Enable, 0, [SCInHeader][SCToggle][SCConstValue(1,pixel)], "", "")
SC_float(_Strength, 1.0, [SCRange(0,10)], "Strength", "")
SC_float(_SampleLength, 0.15, [SCRange(0.01,1)], "Sample Length", "")
SC_float(_Power, 1.5, [SCRange(0.5,8)], "Power", "")
SC_color(_AOColor, (0,0,0,1), [], "AO Color", "")
SC_Box
SC_uint(_Quality, 2, [SCEnum(Low,1,Medium,2,High,3,Ultra,4)][SCConstValue(4,pixel)], "Quality", "")
SC_uint(_Dither, 1, [SCToggle][SCConstValue(1,pixel)], "Dither", "")
SC_float(_Bias, 0.02, [SCRange(0,0.2)], "Bias", "")
SC_float(_MinDistance, 0.001, [SCRange(0,0.1)], "Min Distance", "")
SC_float(_MaxDistance, 0.5, [SCRange(0.01,2)], "Max Distance", "")
SC_float(_FadeDistance, 15.0, [SCRange(1,50)], "Fade Distance", "")
SC_uint(_DisableInMirror, 1, [SCToggle], "Disable in Mirror", "")
SC_BoxEnd
SC_uint(_MaskChannel, 3, [SCMaskChannel], "__MaskChannel", "")
